### PR TITLE
Merge pull request from mcasperson fork 

### PR DESCRIPTION
**Pull request by dehanw**
Release 1.0.17

### CODE REVIEW

**Comment by dehanw** [comment]
Hi @mcasperson ,
I just found that the step "clicking the element n times" was not working and regarded as undefined at bamboo and the Iridium version in bamboo is 1.0.5 only.  Could you please help have a review? 

Thanks,
Iris

**Review by maraisr — APPROVED** [review]
Not a java guy - but looks pretty good to me.

**Comment by mcasperson** [comment]
@dehanw 

The version of Iridium in Bamboo is typically built from the version of the code in the AutoGeneral git repo, which is a few releases behind the code in my personal repo. Pull requests like this will sync the two and and update Bamboo with the latest changes.

**Comment by dehanw** [comment]
Thanks @mcasperson, @maraisr @idooo. The steps related to calendar date input are all working now.

**Pull request merged**
